[package]
name = "extractdb"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["EthoIRL"]
repository = "https://github.com/EthoIRL/extractdb"
homepage = "https://github.com/EthoIRL/extractdb"
documentation = "https://docs.rs/extractdb"
readme = "README.md"
description = "A thread-safe, in-memory hash store supporting concurrent fetches and writes."
keywords = ["concurrent", "hashset", "database"]
categories = ["database", "concurrency", "data-structures"]

[dependencies]
hashbrown = "0.16.1"
concurrent-queue = "2.5.0"
bitcode = "0.6.8"
rayon = "1.11.0"
chrono = "0.4.42"
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }